# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PayUDecoupledFlow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PayUDecoupledFlow
    pod 'PayUIndia-3DS2-SDK','4.0.0.alpha.2'
    pod 'PayUIndia-TridentityMFA-SDK'

end
